FROM node:18-slim 

RUN useradd -m appuser

WORKDIR /app

COPY --chown=appuser:appuser package*.json tsconfig.json ./

RUN npm install --omit=dev

COPY --chown=appuser:appuser . .

RUN npx tsc

EXPOSE 8000

USER appuser

CMD ["node", "index.js"]